varnish:
    type: varnish:6.0
    relationships:
        application: 'app:http'
    configuration:
        vcl: !include
            type: string
            path: config.vcl
files:
    type: network-storage:1.0
    disk: 256

rediscache:
    type: redis:5.0

    